#--------------------------
version: '3.8'
#--------------------------
services:
  # == DB =====================
  db:
    image: postgres:13.18-alpine3.20
    container_name: db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - mynetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  #== Backend =================
  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - .env
    environment:
      DB_URL: ${DB_URL}
      DB_LOGIN: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      - db
  #== Frontend ================
  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
    container_name: frontend
    env_file:
      - .env
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - mynetwork
    depends_on:
      - backend
# == Networks =================
networks:
  mynetwork:
    driver: bridge
# == Volumes ==================
volumes:
  postgres_data:
#--------------------------
