#--------------------------
version: '3.8'
#--------------------------
services:
#--------------------------
  db:
    image: postgres:13.18-alpine3.20
    restart: always
    container_name: db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
  #--------------------------
  backend:
    container_name: backend
    build:
      context: ./backend
    restart: always
    env_file:
      - .env
    environment:
      DB_URL: ${DB_URL}
      DB_LOGIN: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - db
  #--------------------------
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    env_file:
      - .env
    environment:
      REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}
      REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "3000:3000"
    depends_on:
      - backend
#--------------------------
