# == Service ===========================================
apiVersion: v1
kind: Service
# ----------------------------
metadata:
  name: backend
  labels:
    app: backend
# ----------------------------
spec:
  selector:
    app: backend
  type: ClusterIP
  # ----------------------------
  ports:
  - name: backend
    port: 8080
    targetPort: 8080
  # ----------------------------
