name: CD_Launching_K8s

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  repository_dispatch:
    types:
      - trigger-k8s

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    ######################################################
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    ######################################################
    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
    ######################################################
    - name: Creating app-config.yml file with envs
      run: |
        cat <<EOF > app-config.yml
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: app-config
          namespace: default
        data:
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          DB_URL: ${{ secrets.DB_URL }}
          SPRING_PROFILES_ACTIVE: prod
        EOF
    ######################################################
    - name: Configure kubectl for EKS
      run: aws eks update-kubeconfig --region eu-central-1 --name k8s-EKS
    ######################################################
    - name: Setup k8s configuration
      working-directory: ./EKS/k8s
      run: bash launch_k8s.sh
    ######################################################
