name: CD_Terraform-AWS

on:
  workflow_run:
    workflows:
      - CI_Testing_Frontend_and_Backend
    types:
      - completed

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # == Configure AWS ===================================
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    # == Install Terraform ===============================
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.0
    # == Configure Terraform/Initialize/Validate =========
    - name: Setting Terraform's env
      env:
        AWS_EKS_CLUSTER_NAME: ${{ secrets.AWS_EKS_CLUSTER_NAME }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_VPC_CIDR: ${{ secrets.AWS_VPC_CIDR }}

        AWS_PUBLIC_SUBNET_1: ${{ secrets.AWS_PUBLIC_SUBNET_1 }}
        AWS_PUBLIC_SUBNET_2: ${{ secrets.AWS_PUBLIC_SUBNET_2 }}

        AWS_PRIVATE_SUBNET_1: ${{ secrets.AWS_PRIVATE_SUBNET_1 }}
        AWS_PRIVATE_SUBNET_2: ${{ secrets.AWS_PRIVATE_SUBNET_2 }}

        AWS_INTRA_SUBNET_1: ${{ secrets.AWS_INTRA_SUBNET_1 }}
        AWS_INTRA_SUBNET_2: ${{ secrets.AWS_INTRA_SUBNET_2 }}
      working-directory: ./EKS/terraform
      run: |
        terraform init && terraform validate
    # == Plan Terraform changes ==========================
    - name: Terraform Plan
      working-directory: ./EKS/terraform
      run: terraform plan
    # # == Launch Terraform ================================
    # - name: Run Terraform
    #   working-directory: ./EKS/terraform
    #   run: terraform apply --auto-approve
    # # == ===
    # - name: Wait 3m to launch k8s locally
    #   run: sleep 180
    # # == Delete everything ===============================
    # - name: Deleting everything
    #   working-directory: ./EKS/terraform
    #   run: terraform destroy --auto-approve
