name: CD_Terraform-AWS

on:
  workflow_run:
    workflows:
      - CI_Testing_Frontend_and_Backend
    types:
      - completed

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    ######################################################
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    ######################################################
    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
    ######################################################
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.0
    ######################################################
    - name: Configure/Initialize/Validate Terraform
      working-directory: ./EKS/terraform
      run: terraform init && terraform validate && terraform plan
    ######################################################
    # - name: Run Terraform
    #   working-directory: ./EKS/terraform
    #   run: terraform apply --auto-approve
    # ######################################################
    # - name: Configure kubectl for EKS
    #   run: aws eks update-kubeconfig --region eu-central-1 --name k8s-EKS
    # ######################################################
    # - name: Setup k8s configuration
    #   working-directory: ./EKS/k8s
    #   run: bash launch_kubernetes.sh
    # ######################################################
    # - name: Wait 2m to launch k8s locally
    #   run: sleep 120
    # ######################################################
    # - name: Deleting everything
    #   working-directory: ./EKS/terraform
    #   run: terraform destroy --auto-approve
    ######################################################
