name: CI_Testing_Frontend_and_Backend

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  repository_dispatch:
    types:
      - trigger-ci-cd

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    ######################################################
    - name: Creating .env file with necessary envs
      run: |
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
        echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
        echo "DB_URL=${{ secrets.DB_URL }}" >> .env
        echo "SPRING_PROFILES_ACTIVE=${{ secrets.SPRING_PROFILES_ACTIVE }}" >> .env
        echo "REACT_APP_BASE_URL=${{ secrets.REACT_APP_BASE_URL }}" >> .env
        echo "DOCKER_LOGIN=${{ secrets.DOCKER_LOGIN }}" >> .env
    ######################################################
    - name: Setup all infrastructure
      run: docker compose up -d
    ######################################################
    - name: Waiting 10sec
      run: sleep 10
    ######################################################
    - name: Check db' tables
      run: docker exec db psql -U "${{ secrets.POSTGRES_USER }}" -d "${{ secrets.POSTGRES_DB }}" -c "\dt"
    ######################################################
    - name: Check frontend' logs
      run: docker logs frontend
    ######################################################
    - name: Check backend' logs
      run: docker logs backend
    ######################################################
    - name: Testing website
      uses: cypress-io/github-action@v6
      env:
        CYPRESS_BASE_URL: http://localhost:80
      with:
        working-directory: ./.github/tests
    ######################################################
    - name: Trigger CD Workflow
      if: ${{ success() }}
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.ACCESS_REPO_TOKEN }}" \
          https://api.github.com/repos/DolVladzio/provedcode_CI-CD/dispatches \
          -d '{"event_type": "trigger-k8s"}'
