name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
#    - name: Build the backend' Dockerfile to test
#      run: docker build -t java ./backend
    - name: Setup an infrastructure
      run: docker compose up -d && docker compose ps
