name: Testing frontend and backend

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # == Test the frontend ====================================
    - name: Build the backend' Dockerfile
    # to test(dev)
    # to launch(prod)
      run: docker build --build-arg SPRING_PROFILES_ACTIVE=dev -t backend ./backend/
    # == Test the frontend ====================================
    - name: Build the frontend' Dockerfile to test
      run: docker build -t frontend ./frontend
