name: Testing frontend and backend

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # # == Setup the whole infrastructure =====================
    - name: Setup all infrastructure
      run: docker compose up -d
    # == Wait 10sec to get backend' logs ======================
    - name: Waiting 10sec
      run: sleep 10
    # == Looking for any error/issues =========================
    - name: Check frontend' logs
      run: docker logs frontend
    # == Looking for any error/issues =========================
    - name: Check backend' logs
      run: docker logs backend
    # == Login to the DockerHub ===============================
    - name: Login to the DockerHub
      run: docker login -u "${{ secrets.DOCKER_LOGIN }}" -p "${{ secrets.DOCKER_PASSWORD }}"
