name: Testing frontend and backend

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # == Create .env file and set all necessary envs ==========    
    #- name: Creating .env file with necessary envs
      #run: |
        #echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
        #echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
        #echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
        #echo "DB_URL=${{ secrets.DB_URL }}" >> .env
        #echo "SPRING_PROFILES_ACTIVE=${{ secrets.SPRING_PROFILES_ACTIVE }}" >> .env
        #echo "REACT_APP_BASE_URL=${{ secrets.REACT_APP_BASE_URL }}" >> .env
    # == Setup the whole infrastructure =======================
    - name: Setup all infrastructure
      run: |
        POSTGRES_USER=${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB=${{ secrets.POSTGRES_DB }}
        DB_URL=${{ secrets.DB_URL }}
        echo "SPRING_PROFILES_ACTIVE=${{ secrets.SPRING_PROFILES_ACTIVE }}" >> .env
        REACT_APP_BASE_URL=${{ secrets.REACT_APP_BASE_URL }}
        docker compose up -d
    # == Wait 10sec to get backend' logs ======================
    - name: Waiting 10sec
      run: sleep 10
    # == Looking for any error/issues =========================
    - name: Check frontend' logs
      run: docker logs frontend
    # == Looking for any error/issues =========================
    - name: Check backend' logs
      run: docker logs backend
    # == Login to the DockerHub ===============================
    - name: Login to the DockerHub
      run: docker login -u "${{ secrets.DOCKER_LOGIN }}" -p "${{ secrets.DOCKER_PASSWORD }}"
