name: Testing frontend and backend

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # == Test the frontend ====================================
    - name: Build the backend' Dockerfile
      run: docker build --build-arg SPRING_PROFILES_ACTIVE=dev -t backend ./backend/
    # == Test the frontend ====================================
    - name: Build the frontend' Dockerfile
      run: docker build -t frontend ./frontend
    # == Setup the whole infrastructure =======================
    - name: Setup all infrastructure
      run: docker compose up -d
    # == ===
    - name: Waiting 10sec 
      run: sleep 10
    # == Looking for any error/issues =========================
    - name: Check frontend' logs
      run: docker logs frontend
    # == Looking for any error/issues =========================
    - name: Check backend' logs
      run: docker logs backend
