name: Testing frontend and backend

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # == Test the frontend ====================================
    - name: Build the backend' Dockerfile
    # to test(dev)
    # to launch(prod)
      run: docker build --build-arg SPRING_PROFILES_ACTIVE=prod -t backend ./backend/
    # == Test the frontend ====================================
    - name: Build the frontend' Dockerfile
      run: docker build -t frontend ./frontend
    # == Setup the whole infrastructure =======================
    - name: Setup all infrastructure
      run: docker compose up -d
    # == Frontend' logs =======================================
    - name: Show frontend' logs
      run: docker logs frontend
    # == Backend' logs ========================================
    - name: Show backend' logs
      run: docker logs backend
